# Generated by Django 3.0.7 on 2020-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_algorithm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='run_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='metrics',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
